Remove unnecessary files
askprep/askprep-portal pull request #2
Opened 2020-02-27 19:09 UTC by hayuna

2020-02-28 20:17 UTC, AnBera requested changes
a basic liting setup would be helpful.

2020-02-28 20:17 UTC, AnBera commented on src/index.js
> +import React from "react";
Can we stick to the single quote for string. Also can we do a basic setup for linting.
I would recomment to follow airbnb rules.. The .eslintrc file look something like this

```
{
  "extends": "airbnb",
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jquery": true,
    "jest": true
  },
  "rules": {
    "react/jsx-filename-extension": 0,
    "jsx-a11y/label-has-for": 0,
    "jsx-a11y/label-has-associated-control": 0
  }
}
```

2020-02-28 20:17 UTC, AnBera commented on package.json
> -    "semantic-ui-react": "^0.88.2"
Looks good. If we need sematic Ui react we will add later

2020-02-28 23:37 UTC, hayuna commented
package-lock.json / yarn.lock should be added to repository only if we are using specific version of packages.

2020-02-29 06:20 UTC, AnBera approved these changes

2020-02-29 06:21 UTC, merged